-- MySQL version
DROP TABLE Alumnus_WorkHistory;
DROP TABLE Member_WorksOn_Project;
DROP TABLE Member_Joins_Group;
DROP TABLE Project;
DROP TABLE Event;
DROP TABLE Group;
DROP TABLE Club;
DROP Table Member;